#+STARTUP: hidestars
#+STARTUP: odd
*Design decisions*
* C Code
*** Use C99 to full extent.
*** Use gcc specific extensions only when necessary.
    Currently used:
    - computed goto
    - __alignof
*** A cell may contain both an int and a pointer
    The basic Forth data type, the cell, becomes the smallest integer
    type with at least as many bytes to store both an int or a void*.

    This will make it possible to interface to C functions in a
    machine-independent and efficient way: It will always be possible
    to store an int, a char or any pointer e.g. on the stack.
* Forth vocabulary
*** Normal Forth words are in lower case.
    This makes it much easier to switch between Forth and other
    applications.
*** "Create"-like words begin with a capital letter.
*** Control structure words like IF and WHILE are capitalised
    This is a kind of convention in Forth Code and it lets them stand
    out.
*** There are no words that handle double integers.
    The C integers are large enough for us. [From GraspForth]
*** Strings are null-terminated, as in C
